modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET

  http_2xx_4xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200,404]
      method: GET

  tcp_check:
    prober: tcp
    timeout: 5s